cases/urls.py
from django.conf.urls import url

from views import (
    CaseCVS,
    Case,
    CaseApi,
    CaseUpdateApi,
    GanttEvents,
    GanttEventsApi,
    SpeedTestCase,
    EventsMonth,
    ListCases
)


urlpatterns = [
    url(r'^case/(?P<pk>\d+)/$',
        Case.as_view(),
        name="Case"),
    url(r'^case-excel/$', CaseCVS, name="ExcelCaseCVSEmpty"),
    url(r'^case-excel/id=(?P<pk>\d+)/$', CaseCVS, name="ExcelCaseCVS"),
    url(r'^case-api/(?P<pk>\d+)/$',
        CaseApi.as_view(),
        name="CaseApi"),
    url(r'^case-update-api/(?P<pk>\d+)/$',
        CaseUpdateApi.as_view(),
        name="CaseUpdateApi"),
    url(r'^gantt/(?P<pk>\d+)$', GanttEvents.as_view(), name="ganttEvents"),
    url(r'^gantt-api/(?P<pk>\d+)$',
        GanttEventsApi.as_view(),
        name="ganttEventsApi"),
    url(r'^events_month-api/(?P<pk>\d+)$',
        EventsMonth.as_view(),
        name="monthEventsApi"),
    url(r'^speed-test-case$', SpeedTestCase.as_view(), name="SpeedTestCase"),

    url(r'^list/$', ListCases.as_view(), name="CasesList"),
]

general/urls.py
from django.conf.urls import url

from views import (Dashboard, AboutUs, BlockedSitesApi, BlockedDomainsApi,
                   BlockedUrlsSites, BlockedDomainsTableCVS,
                   BlockedSitesTableCVS, MapApi, MapVenezuela, MapTableCVS,
                   CaseList, SearchResultCVS, SearchResultFilterCVS,
                   searchTwitterApi, CaseListAdvanced,
                   CaseListApi, ISPListApi, CategoryListApi, RegionListApi,
                   SiteListApi, Home)


urlpatterns = [

    url(r'^dashboard$', Dashboard.as_view(), name="Dashboard"),
    url(r'^about-us$', AboutUs.as_view(), name="AboutUs"),
    url(r'^blocked-sites-api$',
        BlockedSitesApi.as_view(),
        name="BlockedSitesApi"),
    url(r'^blocked-domains-api$',
        BlockedDomainsApi.as_view(),
        name="BlockedDomainsApi"),
    url(r'^blocked-domains_sites$',
        BlockedUrlsSites.as_view(),
        name="BlockedUrlsSites"),
    url(r'^blocked-domains-excel/$',
        BlockedDomainsTableCVS,
        name="ExcelBlockedDomains"),
    url(r'^blocked-sites-excel/$',
        BlockedSitesTableCVS,
        name="ExcelBlockedSites"),
    url(r'^isp-list', ISPListApi.as_view(), name="ISPListApi"),
    url(r'^category-list', CategoryListApi.as_view(), name="CategoryListApi"),
    url(r'^site-list', SiteListApi.as_view(), name="SiteListApi"),
    url(r'^region-list', RegionListApi.as_view(), name="RegionListApi"),
    url(r'^map-Venezuela/$', MapVenezuela.as_view(), name="MapVenezuela"),
    url(r'^map-api', MapApi.as_view(), name="MapApi"),
    url(r'^map-excel/$', MapTableCVS, name="ExcelMap"),
    url(r'^list-cases/title=(?P<title>(\S|\W)*)&category=' + 
        '(?P<category>(\S|\W)*)&start_date=(?P<s_year>\d*)-(?P<s_month>\d*)-' + 
        '(?P<s_day>\d*)&end_date=(?P<e_year>\d*)-(?P<e_month>\d*)-' + 
        '(?P<e_day>\d*)&region=(?P<region>(\S|\W)*)&site=(?P<site>(\S|\W)*)' + 
        '&isp=(?P<isp>(\S|\W)*)/$',
        CaseList.as_view(),
        name="CaseList"),
    url(r'^advanced-list-cases/title=(?P<title>(\S|\W)*)&category=' + 
        '(?P<category>(\S|\W)*)&start_date=(?P<s_year>\d*)-(?P<s_month>\d*)' + 
        '-(?P<s_day>\d*)&end_date=(?P<e_year>\d*)-(?P<e_month>\d*)-' + 
        '(?P<e_day>\d*)&region=(?P<region>(\S|\W)*)&site=(?P<site>(\S|\W)*)' + 
        '&isp=(?P<isp>(\S|\W)*)/$',
        CaseListAdvanced.as_view(),
        name="CaseListAdvanced"),
    url(r'^advanced-list-cases/$',
        CaseListAdvanced.as_view(),
        name="CaseListEmptyAdvanced"),
    url(r'^list-cases-excel/$',
        SearchResultCVS,
        name="ExcelCaseListEmptyAdvanced"),
    url(r'^list-cases-excel/title=(?P<title>(\S|\W)*)&category=' + 
        '(?P<category>(\S|\W)*)&start_date=(?P<s_year>\d*)-(?P<s_month>\d*)' + 
        '-(?P<s_day>\d*)&end_date=(?P<e_year>\d*)-(?P<e_month>\d*)-' + 
        '(?P<e_day>\d*)&region=(?P<region>(\S|\W)*)/$',
        SearchResultFilterCVS,
        name="ExcelCaseListAdvanced"),
    url(r'^list-cases/$', CaseList.as_view(), name="CaseListEmpty"),
    url(r'^cases-api', CaseListApi.as_view(), name="CaseListApi"),
    url(r'^twitter-api/$',
        searchTwitterApi.as_view(),
        name="SearchTwitterApiEmpty"),
    url(r'^twitter-api/search_twitter=(?P<twitterSearch>(\S|\W)*)$',
        searchTwitterApi.as_view(),
        name="SearchTwitterApi"),
]

stylingGuide/urls.py
from django.conf.urls import url

from stylingGuide.views import (Typography, Elements, List, ListApi)


urlpatterns = [
    url(r'^typography', Typography.as_view()),
    url(r'^elements', Elements.as_view()),
    url(r'^list', List.as_view(), name="List"),
    url(r'^list-api', ListApi.as_view(), name="ListApi"),
]

vsfWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from general.views import Home

urlpatterns = [
    url(r'^$', Home.as_view(), name="Home"),
    url(r'^admin/', admin.site.urls),
    url(r'^cases/', include('cases.urls', namespace="Cases")),
    url(r'^general/', include('general.urls', namespace="General")),
    url(r'^provider/', include('provider.urls', namespace="Provider")),
    url(r'^summary/', include('summary.urls', namespace="Summary")),
    url(r'^styling-guide/',
        include('stylingGuide.urls',
                namespace="StylingGuide")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

general/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

general/views.py
import csv
import datetime
import json
import urllib2

from django.conf import settings
from django.http import HttpResponse
from django.template.defaultfilters import title
from django.utils.http import urlquote
from django.views.generic import (TemplateView)
from rest_framework.response import Response
from rest_framework.views import APIView
import requests
from django.forms.forms import Form


class Home(TemplateView):
    """ This view renders the HTML containing information about the company,
        social network, etc.
    """
    template_name = "home.html"


class AboutUs(TemplateView):
    """ This view renders the HTML containing information about the company,
        social network, etc.
    """
    template_name = "about-us.html"


class ISPListApi(APIView):
    """This view obtains the list of isp json data from the API of the
        Pandora project
    """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/isp/',
            headers=headers)
        return Response(snippet)


class CategoryListApi(APIView):
    """This view obtains the list of isp json data from the API of the
        Pandora project
    """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/category/',
            headers=headers)
        return Response(snippet)


class SiteListApi(APIView):
    """This view obtains the list of isp json data from the API of the
        Pandora project
    """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/events/api/site/',
            headers=headers)
        return Response(snippet)


class RegionListApi(APIView):
    """This view obtains the list of isp json data from the API of the
        Pandora project
    """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/region/',
            headers=headers)
        return Response(snippet)


class BlockedSitesApi(APIView):
    """This view obtains the blocked sites json data from the API of the
        Pandora project
    """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/events/api/blocked_sites/',
            headers=headers)
        return Response(snippet)


class BlockedDomainsApi(APIView):
    """ This view obtains the blocked domains json data from the API of the
    Pandora project """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/events/api/blocked_domains/',
            headers=headers)
        return Response(snippet)


def BlockedDomainsTableCVS(request):
    """ This view takes list of filtered cases and exports it to a CVS file."""
    # Get the list of all the cases and load it as JSON
    headers = {'Authorization': settings.SERVICES_TOKEN}
    snippet = requests.get(
        settings.URL_VSF +
        '/events/api/blocked_domains/',
        headers=headers)
    data = json.loads(snippet.text)

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response[
        'Content-Disposition'] = ('attachment;' +
                                  ' filename="BlockedDomainsTable.csv"')

    # CSV header.
    writer = csv.writer(response)
    writer.writerow(['Fecha descarga', 'Domains'])
    # count is the total of cases to be shown.
    # result is where the information is located in the JSON
    result = data['results']
    count = data["count"] - 1

    # Load all the information of each result in a CVS row
    while (count > -1):
        site = result[count]['site']
        url = result[count]['url']

        download_date = datetime.datetime.now().date()

        writer.writerow([download_date, site, url])
        count = count - 1

    return response


def BlockedSitesTableCVS(request):
    """ This view takes list of filtered cases
    and exports it to a CVS file. """
    # Get the list of all the cases and load it as JSON
    headers = {'Authorization': settings.SERVICES_TOKEN}
    snippet = requests.get(
        settings.URL_VSF +
        '/events/api/blocked_sites/',
        headers=headers)
    data = json.loads(snippet.text)

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response[
        'Content-Disposition'] = 'attachment; filename="BlockedSitesTable.csv"'

    # CSV header.
    writer = csv.writer(response)
    writer.writerow(['Fecha descarga', 'Site', 'Domains'])
    # count is the total of cases to be shown.
    # result is where the information is located in the JSON
    result = data['results']
    count = data["count"] - 1

    # Load all the information of each result in a CVS row
    while (count > -1):
        site = result[count]['name']

        domains = result[count]['domains']

        countDomains = 0
        domainsList = ""
        for domain in domains:
            if countDomains > 0:
                domainsList = domainsList + ";" + "ID:" + \
                    str(domain["id"]) + ", url: " + domain["url"]
            else:
                domainsList = "ID:" + \
                    str(domain["id"]) + ", url: " + domain["url"]

        countDomains = countDomains + 1

        download_date = datetime.datetime.now().date()

        writer.writerow([download_date, site, domainsList])
        count = count - 1

    return response


class BlockedUrlsSites(TemplateView):
    """ This view renders the HTML containing information about the blocked
    sites and domains."""
    template_name = "blocked-sites_domains.html"


class CaseList(TemplateView):
    """ This view renders the HTML containing information
    about list of cases """
    template_name = "list-cases.html"


class CaseListAdvanced(TemplateView):
    """ This view renders the HTML containing information
    about list of cases """
    template_name = "list-cases-advanced.html"


class CaseListApi(APIView):
    """ This view obtains the list of cases json data from the API
    of the Pandora project """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/list-case-filter/',
            headers=headers)
        return Response(snippet)

    def post(self, request, format=None):
        title = request.data["title"]
        region = request.data["region"]
        category = request.data["category"]
        start_date = request.data["start_date"]
        end_date = request.data["end_date"]
        isp = request.data["isp"]
        site = request.data["site"]

        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/list-case-filter/?title=' +
            title +
            "&category=" +
            category +
            '&start_date=' +
            start_date +
            '&end_date=' +
            end_date +
            '&region=' +
            region +
            '&site=' +
            site +
            '&isp=' +
            isp,
            headers=headers)
        return Response(snippet)


class Dashboard(TemplateView):
    """ This view renders the HTML containing the dashboard """
    template_name = "dashboard.html"


class MapVenezuela(TemplateView):
    """ This view renders the HTML containing information
    about map with its cases per region."""
    template_name = "maps/venezuela.html"


class MapApi(APIView):
    """ This view obtains the maps json data from the API
    of the Pandora project """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/list/region/',
            headers=headers)
        return Response(snippet)


def MapTableCVS(request):
    """ This view takes list of the cases per region and its total per region
     and exports it to a CVS file."""
    # Get the list of all the cases and load it as JSON
    headers = {'Authorization': settings.SERVICES_TOKEN}
    snippet = requests.get(
        settings.URL_VSF +
        '/cases/api/list/region/',
        headers=headers)
    data = json.loads(snippet.text)

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response[
        'Content-Disposition'] = ('attachment;' +
                                  'filename="BlockedSitesPerRegion.csv"')

    # CSV header.
    writer = csv.writer(response)
    writer.writerow(['Fecha descarga', 'Region', 'Numero de casos', 'Casos'])
    # count is the total of cases to be shown.
    # result is where the information is located in the JSON
    result = data['results']
    count = data["count"] - 1

    # Load all the information of each result in a CVS row
    while (count > -1):
        region = result[count]['name']
        number_cases = result[count]['number_cases']

        cases = result[count]['cases']

        countCases = 0

        casesList = ""
        for case in cases:

            if countCases > 0:

                casesList = casesList + ";" + "ID:" + \
                    str(case["id"]) + ", Title: " + case["title"] + \
                    ", Category: " + case['category']['display_name']
            else:

general/templates/about-us.html
{% extends "base.html" %}


{% block content %}

    About us here!
    Under construction!

{% endblock content %}

general/templates/dashboard.html
{% extends "base.html" %}


{% block content %}

    Dashboard here!
    Under construction!
    
{% endblock content %}

general/templates/list-cases-advanced.html
{% extends "base.html" %} 
{% load static %} 
{% load i18n %} 
{% block content %} 
{% get_current_language as language_code %}

<link rel="stylesheet" type="text/css"
	href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />


<script type="text/javascript"
	src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>


<!-- Include Date Range Picker -->
<script type="text/javascript"
	src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>

<!-- Global variables corresponding to the search fields from the URL parameters -->
<input type="hidden" id="hidden_title" value="{{ title }}">
<input type="hidden" id="hidden_category" value="{{ category }}">
<input type="hidden" id="hidden_region" value="{{ region }}">
<input type="hidden" id="hidden_site" value="{{ site }}">
<input type="hidden" id="hidden_isp" value="{{ isp }}">
<input type="hidden" id="hidden_label" value="">
<input type="hidden" id="hidden_start_date"
	value="{{ s_year }}-{{ s_month }}-{{ s_day }}">
<input type="hidden" id="hidden_end_date"
	value="{{ e_year }}-{{ e_month }}-{{ e_day }}">
<input type="hidden" id="hidden_url_web" value="{{VSF_URL_WEB}}">
<input type="hidden" id="hidden_search_results_string" value="{% trans 'Search Results' %}">
<input type="hidden" id="hidden_result_string" value="{% trans 'Results' %}">
<input type="hidden" id="hidden_of" value="{% trans 'of' %}">


<div class="container-fluid">


	<div class="row">


		<div class="bodyContent">
			<!-- Search bar form -->
			<form id="advanced_search">
				{% csrf_token %}
				<div class="col-xs-12">
					<div class="col-xs-8 first ">

						<div class="col-xs-9">
							<input type="text" id="title" name="title" placeholder="{% trans 'Title' %}">
						</div>

						<div id="reportrange" class="col-xs-2"
							style="cursor: pointer; padding: 5px 10px;">
							<span></span> <b class="caret"></b> <i
								class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
						</div>

						<div class="col-xs-1">
							<input type="submit" value="" id="submit" />


						</div>

					</div>
				</div>
				<div class="col-xs-12 multipleChoices">

					<select id="isp" data-placeholder="{% trans 'ISP' %}" multiple="">
				
					</select> 
					
					<select id="category" data-placeholder="{% trans 'Category' %}" multiple="">

					</select> 
					
					<select id="region" data-placeholder="{% trans 'Region' %}" multiple="">

					</select> 
					
					<select id="site" data-placeholder="{% trans 'Site' %}" multiple="">

					</select>



				</div>



				<input type="hidden" id="start_date" class="datepicker"
					name="start_date" placeholder="Start date"> 
				<input
					type="hidden" id="end_date" class="datepicker" name="end_date"
					placeholder="End date">






			</form>

			<br>
		</div>




	</div>

</div>

<div class="container-fluid" style="height: 100vh; background: #DEDEDE">

	<div class="bodyContent">

		<div style="margin-bottom: 10px">


			<!-- Search results -->
			<div class="listCasesContainer">
				<div class="col-xs-12 resumeResult">
					<div id="resultados" class="col-xs-8 resultadosAdvanced"></div>
					<div class="col-xs-2">
						{% trans 'Download:' %} <a id="download" href="#"><i
							class="fa fa-file-excel-o" aria-hidden="true"></i></a>
					</div>

					<div class="col-xs-2 advancedSearchText">Vista avanzada</div>


				</div>

				<div class="col-xs-12 subtitleBar" style="background: transparent">
					<div class="h4Style title" style="padding-left: 0px;">
						<div class="col-xs-1" id="dateStartClick">Inicio</div>
						<div class="col-xs-1" id="dateEndClick">Fin</div>
						<div class="col-xs-3" id="nameClick">Caso</div>
						<div class="col-xs-1" id="siteClick">Sitio</div>
						<div class="col-xs-1" id="ispClick">ISP</div>
						<div class="col-xs-1" id="categoryClick">Categoria</div>
						<div class="col-xs-1" id="regionClick">Region</div>
					</div>
				</div>

				<div class="listCasesAdvanced"></div>
				<div class="row">
					<span class="offset-xs-5" id="resultSummary"></span>
					<ul id="pagin" class="offset-xs-1" ></ul>
				</div>
				
				
			</div>




		</div>
		
		<br>
		<div class="col-xs-12">
			<ul id="pagin"></ul>
		</div>	

		<div class="changeStyling"></div>

	</div>
</div>

 
<script type="text/javascript">

var hidden_results_string = $("#hidden_search_results_string").val();
// Load the the datepicker style
$(function() {

    var start = moment().subtract(29, 'days');
    var end = moment();

    function cb(start, end, label) {
   
        var start_date = $( "#hidden_start_date" ).val();
        var end_date = $( "#hidden_end_date" ).val();

        if(start_date == "--" & label == "" )
        {
            start_date = " ";
        }
        else if( label != "Custom Range" ) 
        {
            start_date = start_date.split( "-" );
            start_date = start_date[2] + "/" + start_date[1] + "/" + start_date[0];
        }
        else
        {
            start_date = start.format('DD/MM/YYYY');
        }
        
        if(end_date == "--" & label == ""  ){
            end_date = " ";
        }
        else if( label != "Custom Range" ) 
        {
            end_date = end_date.split( "-" );
            end_date = end_date[2] + "/" + end_date[1] + "/" + end_date[0];
        }
        else
        {
            end_date = end.format('DD/MM/YYYY');
        }
        
        $("#start_date").val(start.format('YYYY-MM-DD'));
        $("#end_date").val(end.format('YYYY-MM-DD'));
        
        if(label == "Custom Range"){
            $('#reportrange span').html( start_date + ' - ' + end_date );
            $('#hidden_label').val("Custom Range");
        }
                
        else if(label != "")   
        {
            $('#reportrange span').html( label );
            $('#hidden_label').val(label);
        } 
        else{
             $('#reportrange span').html( start_date + ' - ' + end_date );
             $('#hidden_label').val();
        }
             
        
        
    
    }

    $('#reportrange').daterangepicker({
        autoUpdateInput: false,
        startDate: start,
        endDate: end,
        ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
    }, cb);
    
    var label = $('.daterangepicker .ranges li.active').text();
    
    $(".applyBtn .btn-success").click(function(){
        label="Custom Range";
    })
    
    cb(start, end, label );
    
 
});
</script>



	

<script type="text/javascript">
	
	
	
	
	
	 var url_isp = "{% url 'General:ISPListApi' %}";
	 
	 var url_category = "{% url 'General:CategoryListApi' %}";
	 
	 var url_region = "{% url 'General:RegionListApi' %}";
	 
	 var url_site = "{% url 'General:SiteListApi' %}";
	 
	 var fail_service_img = "{% static 'img/icons/vsf_iconfailure_v101.svg' %}";
 
</script>

<script>
   
    // These variables are the URLs used for the AJAX calls in the list.js file. They need to be specified here 
    // because of DJango configuration
    var url_web = $("#hidden_url_web").val();
    var url_data="{% url 'General:CaseListApi' %}"
    var url_data_search="{% url 'General:CaseListApi' %}"
    var url_data_list_empty="{% url 'General:CaseListEmptyAdvanced' %}"
    var url_csv ="{% url 'General:ExcelCaseListEmptyAdvanced' %}"

    function fillSelectors(selectContainer, url_data, values){
    	
    	$.ajax({
    		url : url_data,
    		method : "GET",
    		dataType : 'json',
    		contentType : 'application/json'
    	})
    	.done(
    			function(data) {
    	
    				var temporal = "";
    	
    				// Forhttp://127.0.0.1:8000/general/advanced-list-cases/title=&category=&start_date=--&end_date=--&region=&site=Fancy&isp= each element in the JSON we
    				// need to collect their values
    				for (var i = 0; i < data.length; i++) {
    					temporal = temporal.concat(data[i]);
    				}
    				
    	
    				var dataJson = JSON.parse(temporal);
    				var $select = $(selectContainer);
    				$.each( dataJson.results, function(key, value) { 
    				// First Level
    					
    					if(selectContainer =="#region"){
    						$.each( value, function(keyLevel, valueLevel) { 
    							
    							if(keyLevel == "name")
    								$select.append('<option value="' + valueLevel + '">' + valueLevel + '</option>');
    							
    						});
    					}
    					else if(selectContainer =="#category"){
    	
    							
							var element = value.category;
							
							$select.append('<option value="' + element.name + '">' +  element.display_name + '</option>');
							
    							
    						
    						}
    						else{
    	    						$.each( value, function(keyLevel, valueLevel) { 
    	    							
    	    							$select.append('<option value="' + valueLevel + '">' + valueLevel + '</option>');
    	    							
    	    						}
    						);
    					}
    					
    				
    				});
    				
    				
    				
    				
    				$select.chosen();
    				
    				if(values!=""){
    					var str_array = values.split(',');
        				
    					for (var i = 0; i < str_array.length; i++) {
    						str_array[i] = str_array[i].replace(/^\s*/, "");
    					}
						
    					$select.val(str_array).trigger("chosen:updated");
        				
    				
    				}
    				else{
    					$select.val("").trigger("chosen:updated");
    				}
    				
    				$("#hidden_" + (selectContainer.split("#"))[1]).val(values);
    		    	
    				
    				$select.change(function(){
    			        var selectedValues = $(this).find('option:selected').map(function(){
    			                                 return this.value;
    			                             }).get();
    
    			        $("#hidden_" + (selectContainer.split("#"))[1]).val(selectedValues);
    			    });
    				
    	}).fail(function(jqXHR, textStatus, errorThrown) {
    		$('.multipleChoices').html("<div class='failedService'><img style='    background: gray;' src='"+ fail_service_img + "' alt='service fail' /><br><p>Failed to load multiselection service</p></div>");
    	});
    	
    }

	
    
		
</script>

<script src="{% static 'js/general/list-cases-advanced.js' %}"></script>
<script>

function pagination(){
	$("#pagin").html("");
	//Pagination
	pageSize = 10;
	
	elementCount = parseInt($('#resultados strong').text());
	
	pageCount = Math.ceil(elementCount / pageSize);

	for (var i = 0; i < pageCount; i++) {
	  if (i == 0)
	    $("#pagin").append('<li class="owl-theme"><a style="background: transparent" class=" owl-dots current" href="#" data-page="'+ (i + 1) + '">' + "<div class='owl-dot'><span></span></div>" + '</a></li>');
	  else
	    $("#pagin").append('<li class="owl-theme"><a style="background: transparent" class=" owl-dots" href="#" data-page="'+ (i + 1) + '">' + "<div class='owl-dot'><span></span></div>" + '</a></li>');
	}
	
	

	showPage = function(page) {
		var string_result = $("#hidden_result_string").val();
		var string_of = $("#hidden_of").val();
		
		if(pageSize < elementCount){
			
			$("#resultSummary").html(string_result + " " + (elementCount-pageSize*(pageCount-page)) + "-" + elementCount + " " + string_of + " " + elementCount)
		}
		else{
			$("#resultSummary").html(string_result + " " + "1-" + elementCount +  " " + string_of + " "  + elementCount)
		}
		
		
		$(".owl-theme .owl-dot").removeClass('active');
		$(".listCases  .smallBar").hide();
		
		
		$(".owl-theme .owl-dot").each(function(n){
			 if (n == (page-1)){
				  $(this).addClass('active');
				  
			  }
		});
	
		$(".listCases .smallBar").each(function(n) {
		  if (n >= pageSize * (page - 1) && n < pageSize * page){
			  $(this).show();
			  
		  }
		    
		  else {
			  $(this).hide();
		  }
			 
		});
	}
	
	
	 

	$("#pagin li a").click(function() {
	  $("#pagin li a").removeClass("current");
	  $(this).addClass("current");
	  
	  showPage(parseInt($(this).data('page')))
	});

	
}
</script>
{% endblock %}