cases/urls.py
from django.conf.urls import url

from views import (
    CaseCVS,
    Case,
    CaseApi,
    CaseUpdateApi,
    GanttEvents,
    GanttEventsApi,
    SpeedTestCase,
    EventsMonth,
    ListCases
)


urlpatterns = [
    url(r'^case/(?P<pk>\d+)/$',
        Case.as_view(),
        name="Case"),
    url(r'^case-excel/$', CaseCVS, name="ExcelCaseCVSEmpty"),
    url(r'^case-excel/id=(?P<pk>\d+)/$', CaseCVS, name="ExcelCaseCVS"),
    url(r'^case-api/(?P<pk>\d+)/$',
        CaseApi.as_view(),
        name="CaseApi"),
    url(r'^case-update-api/(?P<pk>\d+)/$',
        CaseUpdateApi.as_view(),
        name="CaseUpdateApi"),
    url(r'^gantt/(?P<pk>\d+)$', GanttEvents.as_view(), name="ganttEvents"),
    url(r'^gantt-api/(?P<pk>\d+)$',
        GanttEventsApi.as_view(),
        name="ganttEventsApi"),
    url(r'^events_month-api/(?P<pk>\d+)$',
        EventsMonth.as_view(),
        name="monthEventsApi"),
    url(r'^speed-test-case$', SpeedTestCase.as_view(), name="SpeedTestCase"),

    url(r'^list/$', ListCases.as_view(), name="CasesList"),
]

stylingGuide/urls.py
from django.conf.urls import url

from stylingGuide.views import (Typography, Elements, List, ListApi)


urlpatterns = [
    url(r'^typography', Typography.as_view()),
    url(r'^elements', Elements.as_view()),
    url(r'^list', List.as_view(), name="List"),
    url(r'^list-api', ListApi.as_view(), name="ListApi"),
]

summary/urls.py
from django.conf.urls import url


from views import (
    ListCases,
    SummaryTable,
    SummaryCategoryTableCVS,
    SummaryISPTableCVS,
    MeasurementsTable,
    MeasurementsTableCVS,
    SummaryCategoryTableApi,
    SummaryIspTableApi,
    MeasurementsTableApi)


urlpatterns = [
    url(r'^list-cases$', ListCases.as_view()),
    url(r'^summary-table$', SummaryTable.as_view()),
    url(r'^measurements-table/(?P<pk>\d+)/$',
        MeasurementsTable.as_view(),
        name="MeasurementsTable"),
    url(r'^summary-category-api$',
        SummaryCategoryTableApi.as_view(),
        name="SummaryCategoryTableApi"),
    url(r'^summary-isp-api$',
        SummaryIspTableApi.as_view(),
        name="SummaryIspTableApi"),
    url(r'^summary-measurement-api/(?P<pk>\d+)$',
        MeasurementsTableApi.as_view(),
        name="MeasurementsTableApi"),
    url(r'^summary-measurement-excel/(?P<pk>\d+)$',
        MeasurementsTableCVS,
        name="ExcelMeasurementList"),
    url(r'^summary-isp-excel/$', SummaryISPTableCVS, name="ExcelISPList"),
    url(r'^summary-category-excel/$',
        SummaryCategoryTableCVS,
        name="ExcelCategoryList"),
]

vsfWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from general.views import Home

urlpatterns = [
    url(r'^$', Home.as_view(), name="Home"),
    url(r'^admin/', admin.site.urls),
    url(r'^cases/', include('cases.urls', namespace="Cases")),
    url(r'^general/', include('general.urls', namespace="General")),
    url(r'^provider/', include('provider.urls', namespace="Provider")),
    url(r'^summary/', include('summary.urls', namespace="Summary")),
    url(r'^styling-guide/',
        include('stylingGuide.urls',
                namespace="StylingGuide")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

summary/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

summary/views.py
import csv
import datetime
import json

from django.conf import settings
from django.http import HttpResponse
from django.views.generic import (TemplateView)
from rest_framework.response import Response
from rest_framework.views import APIView
import requests


# Create your views here.
class ListCases(TemplateView):
    """ This view renders the HTML of the simple search """
    template_name = "list-cases.html"


class SummaryTable(TemplateView):
    """ This view renders the html of the summary table of the cases """
    template_name = "summary-table.html"


class SummaryTableApi(APIView):
    """ This view renders the API request for the summary table """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/list/',
            headers=headers)
        return Response(snippet)


class SummaryCategoryTableApi(APIView):
    """ This view renders the API request for the summary table
    by category """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/list/category/',
            headers=headers)
        return Response(snippet)


class SummaryIspTableApi(APIView):
    """ This view renders the API request for the summary table
    by isp """

    def get(self, request, format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/list/isp/',
            headers=headers)
        return Response(snippet)


class MeasurementsTable(TemplateView):
    """ This view renders the html of the measurement table of a case  """
    template_name = "measurements-table.html"


class MeasurementsTableApi(APIView):
    """ This view renders the API request for the measurement table
    by category """

    def get(self, request, pk="1", format=None):
        headers = {'Authorization': settings.SERVICES_TOKEN}
        snippet = requests.get(
            settings.URL_VSF +
            '/cases/api/detail_event/' + pk,
            headers=headers)
        return Response(snippet)


def MeasurementsTableCVS(request, pk="1"):
    """ This view takes list of measurements and exports
    it to a CVS file. """
    # Get the list of all the cases and load it as JSON
    headers = {'Authorization': settings.SERVICES_TOKEN}
    snippet = requests.get(
        settings.URL_VSF +
        '/cases/api/detail_event/' + pk,
        headers=headers)
    data = json.loads(snippet.text)

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response[
        'Content-Disposition'] = 'attachment; filename="MeasurementTable.csv"'

    # CSV header.
    writer = csv.writer(response)
    writer.writerow(['Fecha descarga',
                     'Flags'])
    # count is the total of cases to be shown.
    # result is where the information is located in the JSON
    results = data['events']
    count = 0

    for result in results:
        # Load all the information of each result in a CVS row
        flags = result['flags']

        countFlags = 0
        flagsList = ""
        for flag in flags:
            flagsList = "[ " + flagsList + "ID: " + str(flag['id'])
            flagsList = (flagsList + ", Country: " +
                         str(flag['probe']['country']))
            flagsList = flagsList + ", City: " + str(flag['probe']['city'])
            flagsList = flagsList + ", Region: " + str(flag['probe']['region'])
            flagsList = flagsList + ", Type: " + str(flag['type_med'])
            flagsList = flagsList + ", Date: " + str(flag['date'])
            flagsList = flagsList + ", Target: " + str(flag['target']) + " ]"

        download_date = datetime.datetime.now().date()

        writer.writerow([download_date,
                         flagsList])
        count = count + 1

    return response


def SummaryISPTableCVS(request):
    """ This view takes list of cases per ISP and exports
    it to a CVS file. """
    # Get the list of all the cases and load it as JSON
    headers = {'Authorization': settings.SERVICES_TOKEN}
    snippet = requests.get(
        settings.URL_VSF +
        '/cases/api/list/isp/',
        headers=headers)
    data = json.loads(snippet.text)

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="ISPTable.csv"'

    # CSV header.
    writer = csv.writer(response)
    writer.writerow(['Fecha descarga', 'ISP', 'Casos'])
    # count is the total of cases to be shown.
    # result is where the information is located in the JSON
    result = data['results']
    count = data["count"] - 1

    # Load all the information of each result in a CVS row
    while (count > -1):
        isp = result[count]['isp']

        cases = result[count]['cases']

        countCases = 0
        casesList = ""
        for case in cases:
            if countCases > 0:
                casesList = casesList + ";" + "ID:" + \
                    str(case["id"]) + ", Titulo: " + case["title"]
            else:
                casesList = "Casos= ID:" + \
                    str(case["id"]) + ", Titulo: " + case["title"]

        countCases = countCases + 1

        download_date = datetime.datetime.now().date()

        writer.writerow([download_date, isp, casesList])
        count = count - 1

    return response


def SummaryCategoryTableCVS(request):
    """ This view takes list of cases per category and exports
    it to a CVS file. """
    # Get the list of all the cases and load it as JSON
    headers = {'Authorization': settings.SERVICES_TOKEN}
    snippet = requests.get(
        settings.URL_VSF +
        '/cases/api/list/category/',
        headers=headers)
    data = json.loads(snippet.text)

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response[
        'Content-Disposition'] = 'attachment; filename="CategoryTable.csv"'

    # CSV header.
    writer = csv.writer(response)
    writer.writerow(['Fecha descarga', 'Category', 'Casos'])
    # count is the total of cases to be shown.
    # result is where the information is located in the JSON
    result = data['results']
    count = data["count"] - 1

    # Load all the information of each result in a CVS row
    while (count > -1):

        category = result[count]['category']
        cases = result[count]['cases']

        countCases = 0
        casesList = ""
        for case in cases:
            if countCases > 0:
                casesList = casesList + ";" + "ID:" + \
                    str(case["id"]) + ", Titulo: " + case["title"]
            else:
                casesList = "Casos= ID:" + \
                    str(case["id"]) + ", Titulo: " + case["title"]

        countCases = countCases + 1

        download_date = datetime.datetime.now().date()

        writer.writerow([download_date, category, casesList])
        count = count - 1

    return response

summary/templates/measurements-table.html
{% extends "base.html" %} 
{% load i18n %} 
{% load static %}
{% block content %} 
{% get_current_language as language_code %}


<link rel="stylesheet" href="{% static 'css/jjsonviewer.css' %}">
<div class="bodyContent">
	<div class="col-xs-11 marginPage">
		<div class="row">
			<div class="col-xs-2">
				{% trans 'Download:' %} <a id="download" href="#"> <i
					class="fa fa-file-excel-o" aria-hidden="true"></i>
				</a>
			</div>
		</div>
		<div class="container-fluid" id="mTable">
	
			<div class="row">
	
				<div class="col-xs-11" id="headerDiv">
	
					<div class="col-xs-2 mheader">{% trans 'Site' %}</div>
					<div class="col-xs-3 mheader">{% trans 'URL' %}</div>
					<div class="col-xs-1 mheader">{% trans 'Date' %}</div>
					<div class="col-xs-1 mheader">{% trans 'State'%}</div>
					<div class="col-xs-1 mheader">{% trans 'City' %}</div>
					<div class="col-xs-1 mheader">{% trans 'ISP' %}</div>
					<div class="col-xs-1 mheader">{% trans 'Measurement' %}</div>
					<div class="col-xs-2 mheader">{% trans 'Type' %}</div>
	
				</div>
	
			</div>
	
			<div class="row" id="measurementHeaderRow"></div>
	
			<div class="row">
	
				<div class="col-xs-11" id="dataTableM"></div>
	
			</div>
	
		</div>
	</div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
	aria-labelledby="measurementTitle" aria-hidden="true">
	<div class="modal-dialog" id="modalm" role="document">
		<div class="modal-content" id="mModalContent">
			<button type="button" class="close" id="closeButton"
				data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<div class="modal-header" id="mModalHeader">

				<h4 class="modal-title" id="measurementTitle"></h4>

			</div>
			<div class="modal-body" id="measurementData"></div>
			<div class="modal-footer" id="measurementFooter">

				<button type="button" class="btn btn-secondary" id="modalButton"
					data-dismiss="modal">Close</button>

			</div>
		</div>
	</div>
</div>
<script> 
	var pk = {{ pk }}
	var url_data_measurement =  "{% url 'Summary:MeasurementsTableApi' pk=pk %}" 
	var url_excel = "{% url 'Summary:ExcelMeasurementList' pk=pk %}"

		 
	var fail_service_img = "{% static 'img/icons/vsf_iconfailure_v101.svg' %}";
	 
</script>
<script src="{% static 'js/jjsonviewer.js' %}"></script>

<script src="{% static 'js/summary/mtable.js' %}"></script>

{% endblock content %}

summary/templates/summary-table.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
{% get_current_language as language_code %}



<input type="hidden" id="hiddenID" value="" />
<input type="hidden" id="hiddenTitle" value="" />
<input type="hidden" id="category" value="{% trans 'Categories' %}" />
<input type="hidden" id="isp" value="{% trans 'ISPs' %}" />
<input type="hidden" id="hidden_url_web" value="{{VSF_URL_WEB}}">

<div class="bodyContent" style="height: 400px">
<div class="col-xs-6" id="summaryTableBorder">
    <div class="container" id="sumtable">

        <div class="row">


            <table class="table table-hover text-nowrap">

                <thead>

                    <tr>

                        <th id="tabletitle"></th>

                    </tr>

                </thead>

                <tbody id="tablebody">

                </tbody>


                <tfoot>
                    <tr>
                        <td>
                            <button class="contextualButtonFixedSize"
                                onclick="select('category')"
                            >
                                {% trans 'Category' %}</button>

                            <button class="contextualButtonFixedSize" onclick="select('isp')"
                            >
                                {% trans 'ISP' %}</button>
                                
                            <div class="float-xs-right"
                                style="padding-top:1px">
                                {% trans 'Download:' %} <a id="downloadSummary" href="#"> <i
                                    class="fa fa-file-excel-o" aria-hidden="true"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>

        </div>
    </div>
</div>

</div>

<script>
    var url_style_list = "{% url 'StylingGuide:ListApi' %}"
    var url_data_category = "{% url 'Summary:SummaryCategoryTableApi'  %}"
    var url_data_isp = "{% url 'Summary:SummaryIspTableApi' %}"
    var url_excel_category = "{% url 'Summary:ExcelCategoryList' %}"
    var url_excel_isp = "{% url 'Summary:ExcelISPList' %}"
    var url_web = $("#hidden_url_web").val();
</script>

<script src="{% static 'js/summary/table.js' %}"></script>

{% endblock content %}