cases/urls.py
from django.conf.urls import url

from views import (
    CaseCVS,
    Case,
    CaseApi,
    CaseUpdateApi,
    GanttEvents,
    GanttEventsApi,
    SpeedTestCase,
    EventsMonth,
    ListCases
)


urlpatterns = [
    url(r'^case/(?P<pk>\d+)/$',
        Case.as_view(),
        name="Case"),
    url(r'^case-excel/$', CaseCVS, name="ExcelCaseCVSEmpty"),
    url(r'^case-excel/id=(?P<pk>\d+)/$', CaseCVS, name="ExcelCaseCVS"),
    url(r'^case-api/(?P<pk>\d+)/$',
        CaseApi.as_view(),
        name="CaseApi"),
    url(r'^case-update-api/(?P<pk>\d+)/$',
        CaseUpdateApi.as_view(),
        name="CaseUpdateApi"),
    url(r'^gantt/(?P<pk>\d+)$', GanttEvents.as_view(), name="ganttEvents"),
    url(r'^gantt-api/(?P<pk>\d+)$',
        GanttEventsApi.as_view(),
        name="ganttEventsApi"),
    url(r'^events_month-api/(?P<pk>\d+)$',
        EventsMonth.as_view(),
        name="monthEventsApi"),
    url(r'^speed-test-case$', SpeedTestCase.as_view(), name="SpeedTestCase"),

    url(r'^list/$', ListCases.as_view(), name="CasesList"),
]

general/urls.py
from django.conf.urls import url

from views import (Dashboard, AboutUs, BlockedSitesApi, BlockedDomainsApi,
                   BlockedUrlsSites, BlockedDomainsTableCVS,
                   BlockedSitesTableCVS, MapApi, MapVenezuela, MapTableCVS,
                   CaseList, SearchResultCVS, SearchResultFilterCVS,
                   searchTwitterApi, CaseListAdvanced,
                   CaseListApi, ISPListApi, CategoryListApi, RegionListApi,
                   SiteListApi, Home)


urlpatterns = [

    url(r'^dashboard$', Dashboard.as_view(), name="Dashboard"),
    url(r'^about-us$', AboutUs.as_view(), name="AboutUs"),
    url(r'^blocked-sites-api$',
        BlockedSitesApi.as_view(),
        name="BlockedSitesApi"),
    url(r'^blocked-domains-api$',
        BlockedDomainsApi.as_view(),
        name="BlockedDomainsApi"),
    url(r'^blocked-domains_sites$',
        BlockedUrlsSites.as_view(),
        name="BlockedUrlsSites"),
    url(r'^blocked-domains-excel/$',
        BlockedDomainsTableCVS,
        name="ExcelBlockedDomains"),
    url(r'^blocked-sites-excel/$',
        BlockedSitesTableCVS,
        name="ExcelBlockedSites"),
    url(r'^isp-list', ISPListApi.as_view(), name="ISPListApi"),
    url(r'^category-list', CategoryListApi.as_view(), name="CategoryListApi"),
    url(r'^site-list', SiteListApi.as_view(), name="SiteListApi"),
    url(r'^region-list', RegionListApi.as_view(), name="RegionListApi"),
    url(r'^map-Venezuela/$', MapVenezuela.as_view(), name="MapVenezuela"),
    url(r'^map-api', MapApi.as_view(), name="MapApi"),
    url(r'^map-excel/$', MapTableCVS, name="ExcelMap"),
    url(r'^list-cases/title=(?P<title>(\S|\W)*)&category=' + 
        '(?P<category>(\S|\W)*)&start_date=(?P<s_year>\d*)-(?P<s_month>\d*)-' + 
        '(?P<s_day>\d*)&end_date=(?P<e_year>\d*)-(?P<e_month>\d*)-' + 
        '(?P<e_day>\d*)&region=(?P<region>(\S|\W)*)&site=(?P<site>(\S|\W)*)' + 
        '&isp=(?P<isp>(\S|\W)*)/$',
        CaseList.as_view(),
        name="CaseList"),
    url(r'^advanced-list-cases/title=(?P<title>(\S|\W)*)&category=' + 
        '(?P<category>(\S|\W)*)&start_date=(?P<s_year>\d*)-(?P<s_month>\d*)' + 
        '-(?P<s_day>\d*)&end_date=(?P<e_year>\d*)-(?P<e_month>\d*)-' + 
        '(?P<e_day>\d*)&region=(?P<region>(\S|\W)*)&site=(?P<site>(\S|\W)*)' + 
        '&isp=(?P<isp>(\S|\W)*)/$',
        CaseListAdvanced.as_view(),
        name="CaseListAdvanced"),
    url(r'^advanced-list-cases/$',
        CaseListAdvanced.as_view(),
        name="CaseListEmptyAdvanced"),
    url(r'^list-cases-excel/$',
        SearchResultCVS,
        name="ExcelCaseListEmptyAdvanced"),
    url(r'^list-cases-excel/title=(?P<title>(\S|\W)*)&category=' + 
        '(?P<category>(\S|\W)*)&start_date=(?P<s_year>\d*)-(?P<s_month>\d*)' + 
        '-(?P<s_day>\d*)&end_date=(?P<e_year>\d*)-(?P<e_month>\d*)-' + 
        '(?P<e_day>\d*)&region=(?P<region>(\S|\W)*)/$',
        SearchResultFilterCVS,
        name="ExcelCaseListAdvanced"),
    url(r'^list-cases/$', CaseList.as_view(), name="CaseListEmpty"),
    url(r'^cases-api', CaseListApi.as_view(), name="CaseListApi"),
    url(r'^twitter-api/$',
        searchTwitterApi.as_view(),
        name="SearchTwitterApiEmpty"),
    url(r'^twitter-api/search_twitter=(?P<twitterSearch>(\S|\W)*)$',
        searchTwitterApi.as_view(),
        name="SearchTwitterApi"),
]

summary/urls.py
from django.conf.urls import url


from views import (
    ListCases,
    SummaryTable,
    SummaryCategoryTableCVS,
    SummaryISPTableCVS,
    MeasurementsTable,
    MeasurementsTableCVS,
    SummaryCategoryTableApi,
    SummaryIspTableApi,
    MeasurementsTableApi)


urlpatterns = [
    url(r'^list-cases$', ListCases.as_view()),
    url(r'^summary-table$', SummaryTable.as_view()),
    url(r'^measurements-table/(?P<pk>\d+)/$',
        MeasurementsTable.as_view(),
        name="MeasurementsTable"),
    url(r'^summary-category-api$',
        SummaryCategoryTableApi.as_view(),
        name="SummaryCategoryTableApi"),
    url(r'^summary-isp-api$',
        SummaryIspTableApi.as_view(),
        name="SummaryIspTableApi"),
    url(r'^summary-measurement-api/(?P<pk>\d+)$',
        MeasurementsTableApi.as_view(),
        name="MeasurementsTableApi"),
    url(r'^summary-measurement-excel/(?P<pk>\d+)$',
        MeasurementsTableCVS,
        name="ExcelMeasurementList"),
    url(r'^summary-isp-excel/$', SummaryISPTableCVS, name="ExcelISPList"),
    url(r'^summary-category-excel/$',
        SummaryCategoryTableCVS,
        name="ExcelCategoryList"),
]

vsfWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from general.views import Home

urlpatterns = [
    url(r'^$', Home.as_view(), name="Home"),
    url(r'^admin/', admin.site.urls),
    url(r'^cases/', include('cases.urls', namespace="Cases")),
    url(r'^general/', include('general.urls', namespace="General")),
    url(r'^provider/', include('provider.urls', namespace="Provider")),
    url(r'^summary/', include('summary.urls', namespace="Summary")),
    url(r'^styling-guide/',
        include('stylingGuide.urls',
                namespace="StylingGuide")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

commons/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

commons/templates/pdf/case-pdf.html
{% extends "base.html" %} 
{% load i18n %} 
{% load static %} 
{% block content %} 
{% get_current_language as language_code %}

<input id="continueTrans" type="hidden" value="{% trans 'Continua' %}">

<input id="domainTrans" type="hidden" value="{% trans 'Dominios' %}">

<input id="siteTrans" type="hidden" value="{% trans 'Sitios' %}">

<div style="background-color: #DEDEDE; margin-top: 25px;">

	<div class="bodyContent">

		<!-- Basic information of the case -->
		<div class="container-fluid" id="title">
			<div class="row">
				<div class="col-xs-12 titleBar" style="margin-top: 15px">
					<div class="h2Style title" id="titleAjax"></div>
				</div>
			</div>
		</div>


		<div class="container-fluid"
			style="padding-top: 10px; padding-bottom: 40px">
			<div class="row">

				<div class="col-xs-6" id="caseImage"></div>
				
				<div class="col-xs-6" id="caseDescription">
					<div class="h3Style">{% trans "Descripcion: " %}</div>
					<p id="descriptionAjax"></p>
				</div>
			</div>
				
		</div>
	</div>

</div>


<div class="container-fluid white-background padding-title">

	<div class="col-xs-12" id="caseInfo">
					<div class="row subtitleBar" id="dateBar">
						<div class="container-fluid" id="caseDateBar">
							<div class="col-xs-12 timelineBarContinue h4Style">
								<div class="date col-xs-9" id="statusDateAjax"></div>
								<div class="status col-xs-3" id="statusAjax"></div>
							</div>
						</div>
					</div>


					<div class="row">

						<div class="container" id="caseDomainList">
							<div>

								<table class="table table-hover" id="tableDomain">

									<thead>

										<tr>

											<th id="caseCategory" class="h4Style">
											{% trans "Category: "%}</th>

										</tr>


									</thead>


									<tbody id="domainTableBody">

									</tbody>


								</table>

							</div>
						</div>
					</div>

					<div class="row toolbar" id="providerBar">

						<div class="container-fluid" id="caseProvider">

							<div class="col-xs-12" style="text-align: center;" id="ispAjax">

							</div>
						</div>

					</div>
				</div>

	


</div>


<script>
           
    // These variables are the URLs used for the AJAX calls in the list.js file. They need to be specified here 
    // because of DJango configuration
        
        var pk = {{ pk }}
        var domain = "{{ URL_VSF }}"
        var url_case = "{% url 'Cases:Case' pk=pk %}"
        var url_one_case = "{% url 'Cases:CaseApi' pk=pk %}"
        var url_one_case_pdf = "{% url 'Cases:CasePdfEmpty' %}"
        var url_one_case_excel = "{% url 'Cases:ExcelCaseCVSEmpty' %}"
        var url_one_case_update = "{% url 'Cases:CaseUpdateApi' pk=pk %}"

        var language = '{{ language_code }}'
    
        //var png_commons = "{% static "" %}" +"screenshots/screen_case_"+pk+".png"
        var png_commons = "{% static "" %}" +"screenshots/screen_case_"+pk;
         
        var url_data="{% url 'Cases:ganttEventsApi' pk=pk %}"   
        var url_events_month ="{% url 'Cases:monthEventsApi' pk=pk %}"	
        var url_data_twitter ="{% url 'General:SearchTwitterApiEmpty' %}"
        var fail_service_img = "{% static 'img/icons/vsf_iconfailure_v101.svg' %}";
        var fail_twitter_img = "{% static 'img/icons/vsf_icontwitterfailure_v101.svg' %}";
        var url_data_measurements ="{% url 'Summary:MeasurementsTable' pk=pk %}"
        
        
        
        
</script>

<script src="{% static 'js/general/twitter-trending.js' %}"></script>
<script src="{% static 'js/cases/case.js' %}"></script>



<script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
<script type="text/javascript"
	src="http://static.mentful.com/gantt-chart-d3v2.js"></script>

<script src="{% static 'js/d3-timeline/d3-timeline.js' %}"></script>
<script src="{% static 'js/d3-linechart/d3-linechart.js' %}"></script>

{% endblock content %}

commons/templates/pdf/footer.html
{% extends "base.html" %} 
{% load i18n %} 
{% load static %} 
{% block content %} 
{% get_current_language as language_code %}



<div class="container">

	<div class="col-xs-4" id="footerCaseInfo">
	
		<img src="vsf_logolight.svg">
		
	</div>

</div>

{% endblock %}